### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by thebigbone** [blacknon/lssh#133]
Under the `install` in Makefile, the command which removes the previous version of `lssh`, `lscp` and `lsftp` fails because they do not exist. 

![image](https://github.com/blacknon/lssh/assets/95130644/d97441cc-3c82-4347-ad4c-540c3d28039f)

I was able to fix it by using `ifdef` condition which will only remove the files if they do exist and therefore doesn't exit which leads to a fail installation.

**Comment by blacknon** [comment]
Oh, thank you.
I hadn't noticed that, fixed the Makefile in master branch.
