### ISSUE TITLE
Marginのtypo？

### ISSUE THREAD

**Issue by jiro4989** [blacknon/lssh#45]
LeftMerginと定義されていますが、LeftMarginではないでしょうか :question: 

https://eow.alc.co.jp/search?q=margin

https://github.com/blacknon/lssh/blob/277e8667c1b382c27a110f0208b6c832d22e8753/list/struct.go#L18-L23

**Comment by blacknon** [comment]
あ、ホントだ(´・ω・｀)
ありがとうござますー

**Comment by blacknon** [comment]
次のバージョンで修正
