### ISSUE TITLE
Add ServerAliveInterval and ServerAliveCountMax settings

### ISSUE THREAD

**Issue by johnatannvmd** [blacknon/lssh#58]
Thanks for your great tool!

Can you please add ServerAliveCountMax and ServerAliveInterval settings for SSH client?

**Comment by blacknon** [comment]
Thank you Issue!

ServerAliveCountMax and ServerAliveInterval can be added. Incorporate into v0.6.0 currently under development.

**Comment by blacknon** [comment]
Add v0.6.0
