### ISSUE TITLE
Couldn't connect to server via key

### ISSUE THREAD

**Issue by m4xx1m** [blacknon/lssh#97]
I'm using RSA 4096 key.

My config:
![image](https://user-images.githubusercontent.com/59927482/173561583-1a70c2ee-2331-4104-82c7-f66b74b47099.png)

Error:
![image](https://user-images.githubusercontent.com/59927482/173561642-53a8e5ed-c6ad-4b9f-b5d6-ce914c81edc2.png)

![image](https://user-images.githubusercontent.com/59927482/173561726-c83816b2-1ff5-42bd-b76b-b4addc72cd43.png)

**Comment by blacknon** [comment]
Hmm ...
I confirmed it with Version 0.6.7, but it seems that I can log in with the key of RSA4096.

* What the version of lssh?
* Does the RSA 4096 key generation command is `ssh-keygen -t rsa -b 4096`?

**Comment by m4xx1m** [comment]
- lssh version 0.6.7
- yes, I've tried generate new key and using another server, but it didn't work

**Comment by blacknon** [comment]
I'm sorry for being late.

When I checked with Version 0.6.8, I was able to authenticate with RSA8192.
Could you please check it for me?

**Comment by m4xx1m** [comment]
yes, that working, thanks you
